# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: vijay@groundstrokes.org
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Vijay Krishnamurthy, Professor of Sports Management,
  Doctoral candidate in SDMIMD Mysore, founder of Groundstrokes Tennis Academy, former Project
  Manager at PACE, worked on Set Top Box for Tata SKY, trained as a VLSI Electronics Engineer
twitter_username: vjgroundstrokes
github_username: vijaykrishnamurthy-sport
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-158948535-1"
    anonymize_ip: false # default

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Vijay Krishnamurthy"
  avatar : "/assets/images/vijay.jpeg"
  bio    : "Ph.D. Sports Research Scholar"
  links:
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/vjgroundstrokes"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/vijayskrishnamurthy"
    

footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:vijay@groundstrokes.org"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/vjgroundstrokes"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/vijayskrishnamurthy"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
